spring:
  application:
    name: friend_bot
  profiles:
    include:
      - openapi
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,file:src/main/frontend/dist/
server:
  port: 8090
